services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Belog\:
    resource: '../Classes/*'

  TYPO3\CMS\Belog\Module\BackendLogModuleBootstrap:
    public: true
